# GitHub Dependabot configuration file
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directories:
    - "/"
    - ".github/actions/ollama-setup"
    schedule:
      interval: "daily"
