# SPDX-License-Identifier: Apache-2.0

name: 'Additional Test Setup'
description: 'Additional Test Setup for Ollama'
runs:
  using: "composite"
  steps:
    - name: Install Ollama and start server
      shell: bash
      run: |
        curl -fsSL https://ollama.com/install.sh | sudo -E sh

    - name: Wait for Ollama server
      shell: bash
      run: |
        sleep 10
        curl --include --retry 10 --retry-delay 10 --retry-connrefused http://localhost:11434

    - name: Pull Granite models
      shell: bash
      run: |
        ollama pull granite4.1:3b
